### PR TITLE
Add write cache to build log (improve speed)

### PR DESCRIPTION
**Pull request by ss-gxp**
Current logging very slow оn thousands of lines.

### CODE REVIEW

**Comment by corpsee** [comment]
Thanks!

**Comment by corpsee** [comment]
@ss-gxp It doesn't work correct. Build log is not fully save( I reverted changes from master branch

**Comment by ss-gxp** [comment]
Are there any details?
The problem does not appear in my case.
We can assume that saving in the destructor does not work, but not in my case. I'm using crontab to start builds. Since Beanstalkd did not check, this is not your case? Perhaps need forced flush when build done.

(Also I can say that about 22 thousand lines of the log were written about two and a half hours. With a patch in one second.)

**Comment by ss-gxp** [comment]
Added unset log handler to destruct and flush data.
Can you test?

**Comment by corpsee** [comment]
Yes, I use worker. I will check it yonight. Thank you.

**Pull request merged**
