### PR TITLE
Add doc about how to run worker with systemd

### PR DESCRIPTION
**Pull request by ketchoop**
I didn't check this simple unit with PHPCensor server. Just tried to start it. So, it'll be great if you check this more carefully. And maybe I should write more about the unit and how to start it. Anyway, just leave comments about it and I can change it or just do it by yourself:)

### CODE REVIEW

**Comment by corpsee** [comment]
Thanks @ketchoop! I will try to test it soon and will write about it in the issue.

**Comment by ketchoop** [comment]
@ketchoop TODO:
After=network.target
[Install]
WantedBy=multi-user.target

**Comment by corpsee** [comment]
It works if make changes for param `ExecStart`:
```
Environment=PHP_PARAM=php-censor:worker
ExecStart=/var/www/php-censor.local/bin/console $PHP_PARAM
```

**Comment by corpsee** [comment]
My full unit config:
```
[Unit]
Description=PHPCensor Worker
After=network.target

[Service]
Type=simple
Environment=PHP_PARAM=php-censor:worker
ExecStart=/var/www/php-censor.local/bin/console $PHP_PARAM
Restart=always

User=web
Group=www-data

[Install]
WantedBy=multi-user.target
```

**Comment by ketchoop** [comment]
@corpsee why does it need this `Environment=PHP_PARAM=php-censor:worker`?

**Comment by corpsee** [comment]
I don't realy know, but console param `php-censor:worker` doesn't set without `Environment`.

**Comment by ketchoop** [comment]
It works for me. 

```
[Unit]
Description=PHPCensor Worker
After=network.target

[Service]
Type=simple
ExecStart=/your/path/bin/console php-censor:worker
Restart=always

[Install]
WantedBy=multi-user.target
```

Could you restart it and show me `journalctl -r`

**Comment by corpsee** [comment]
It's strange, but now it works. I guess I overconfigurated somewhere :smile:

**Comment by ketchoop** [comment]
@corpsee but what about User and Group? Is it OK for you?

**Comment by corpsee** [comment]
My full config now:
```
[Unit]
Description=PHPCensor Worker
After=network.target

[Service]
Type=simple
ExecStart=/var/www/php-censor.local/bin/console php-censor:worker
Restart=always
User=web

[Install]
WantedBy=multi-user.target
```

**Comment by corpsee** [comment]
And it would be great if we had a unit config to start a few workers simultaneously. I guess we should use `Type=forking`, but I am not sure.

**Comment by ketchoop** [comment]
Type=forking means, that process is daemonized by fork strategy. But what you want can be done by hands with systemd specifiers. Something like `systemctl start php-censor@1.service`. But I need test it and make little changes.

**Comment by ketchoop** [comment]
@corpsee I think, the best and simple way to run several workers is just copy more units with different. I can add docs about this way. Needs you opinion.

**Comment by corpsee** [comment]
@ketchoop It is normal for me. We can update it later if we will have more info.

**Comment by corpsee** [comment]
@ketchoop I suggest to merge it now and update when you have additional information. It will OK?

**Comment by ketchoop** [comment]
@corpsee just check it and feel free to merge :smiley:

**Comment by corpsee** [comment]
I merged it manualy with rebase. Thanks @ketchoop!

**Pull request closed without merging**
