### PR TITLE
Add deploy stage

### PR DESCRIPTION
**Pull request by ss-gxp**
Added separate stage for deploy

### CODE REVIEW

**Comment by corpsee** [comment]
Hi, thank you for the request!

Now you can deploy in `success` stage. Why you want to add `deploy` stage? Can you give a real case for separate stage `deploy`?

**Comment by ket4yii** [comment]
@corpsee I think it's really good idea. In my case, I can't see, when deploy failed, but build is green and it's really annoying. And from point of semantic deployment is not test stage.

**Comment by corpsee** [comment]
Ok, thanks.

**Comment by ss-gxp** [comment]
If deploy fail on success stage, build is succeeded, right?
But different behavior is expected from the system of continuous integration.

**Pull request merged**
